#!/bin/bash

./commit "Making branch $NEWBRANCH"

NEWBRANCH=${1:-default}
NEWBRANCHGIT=${1:-master}

dirs_do(){
  for d in AfriCompta QooxView LibNet Gestion Config Profeda; do
    echo Doing -$1- in $d
    ( cd $d
      $1
    )
  done
}

if ! hg branches | grep -q "^$NEWBRANCH "; then
  echo HG: Branch $NEWBRANCH doesnt exist, creating
  hg branch $NEWBRANCH
  hg commit -m added_branch
fi
if ! git branch | egrep -q "^..$NEWBRANCH"; then
  echo Git: Branch $NEWBRANCHGIT doesnt exist, creating
  git branch $NEWBRANCHGIT
fi

git checkout $NEWBRANCHGIT
hg up -C $NEWBRANCH

