#!/bin/bash

./commit "Making branch $NEWBRANCH"

NEWBRANCH=${1:-default}
NEWBRANCHGIT=${1:-master}

if ! hg branches | grep -q "^$NEWBRANCH "; then
  echo HG: Branch $NEWBRANCH doesnt exist, creating
  hg branch $NEWBRANCH
  hg commit -m added_branch
fi
if ! git branch | egrep -q "^..$NEWBRANCH"; then
  echo Git: Branch $NEWBRANCHGIT doesnt exist, creating
  git branch $NEWBRANCHGIT
fi

git checkout $NEWBRANCHGIT
hg up -C $NEWBRANCH

