#!/bin/bash

./commit "Making branch $NEWBRANCH"

NEWBRANCH=${1:-default}

dirs_do(){
  #  echo Doing -$NEWBRANCH-
  #  return
  for d in AfriCompta QooxView LibNet Gestion Config; do
    echo Doing -$1- in $d
    cd ../$d
    $1
  done
}

if ! hg branches | grep -q "^$NEWBRANCH "; then
  echo HG: Branch $NEWBRANCH doesnt exist, creating
  dirs_do "hg branch $NEWBRANCH"
fi
if ! git branch | egrep -q "^..$NEWBRANCH"; then
  echo Git: Branch $NEWBRANCH doesnt exist, creating
  dirs_do "git branch $NEWBRANCH"
fi

dirs_do "git checkout $NEWBRANCH"
dirs_do "hg up -C $NEWBRANCH"

