#!/bin/bash -e

./commit "Making branch $NEWBRANCH"

BRANCH=${1:-default}
BRANCHGIT=${1:-master}

git merge $BRANCHGIT
hg rev .
hg merge -r $BRANCH
hg commit -m "Merged branch $BRANCH / $BRANCH_GIT"

