#!/bin/bash -e

BRANCH=${1:-default}
BRANCHGIT=${1:-master}
echo "Merging with $BRANCH / $BRANCHGIT"

./commit "Merging with $BRANCH / $BRANCHGIT"

git merge $BRANCHGIT
hg rev .
hg merge -r $BRANCH
hg commit -m "Merged branch $BRANCH / $BRANCH_GIT"

