#!/bin/bash
echo startafricompta
DB=~/.camping

# Initialize variables
cd `dirname $0`
export DIR=$( pwd )
. ./rubylib
echo $RUBYLIB

if [ "$1" = "std" ]; then
  OUT=std
  shift
fi
ARGS=""
if [ "$1" ]; then
  ARGS="--database db.$1"
  DB=$1
  shift
fi
if [ "$1" ]; then
  ARGS="$ARGS -p $1"
fi

# Backing up the DB
./backup_bdd $DB

# Closing old instance
pkill -9 -f compta.rb

mkdir -p Log
LOGFILE=Log/$( date +%y%m%d-%H%M%S ).log
# Starting either in konsole-mode or in nohup
if [ "$OUT" = "std" ]; then
  ./camping $ARGS compta.rb &
else
  nohup ./start_camping $LOGFILE $ARGS &
fi

exit

# Depending on where we are, "open" or "firefox"
if echo "$MACHTYPE" | grep -q apple; then
  sleep 4
  osascript firefox-window.scpt "http://localhost:3301"
else
  zenity --info --text="Un peu de patience" &
  sleep 10
  killall zenity

  firefox http://localhost:3301
fi
